# Generated by Django 3.0.6 on 2020-07-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('mobile_no', models.CharField(max_length=222)),
                ('message', models.TextField()),
            ],
        ),
    ]
