# Generated by Django 3.0.6 on 2020-07-31 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0002_imagepost_videopost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 6, 22, 49, 603507)),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 6, 22, 49, 604507)),
        ),
    ]
