# Generated by Django 3.0.6 on 2020-07-31 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0005_auto_20200731_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 7, 32, 47, 812983)),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 7, 32, 47, 813983)),
        ),
    ]
