# Generated by Django 3.0.6 on 2020-07-31 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0006_auto_20200731_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 7, 36, 0, 365414)),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 7, 36, 0, 365414)),
        ),
    ]
