# Generated by Django 3.0.6 on 2020-07-31 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0007_auto_20200731_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='imagename',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videopost',
            name='videoname',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 12, 8, 43, 533050)),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 12, 8, 43, 534050)),
        ),
    ]
