# Generated by Django 3.0.6 on 2020-07-31 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0009_auto_20200731_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 13, 2, 56, 469388)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(default='static/images/hasntravel.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 31, 13, 2, 56, 471388)),
        ),
    ]
