# Generated by Django 3.0.6 on 2020-08-03 01:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0013_auto_20200803_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 6, 51, 54, 359922)),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 6, 51, 54, 361922)),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postlike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb1.Imagepost')),
            ],
        ),
    ]
