# Generated by Django 3.0.6 on 2020-08-03 02:38

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fb1', '0014_auto_20200803_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 8, 8, 17, 312726)),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 8, 8, 17, 317726)),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
