# Generated by Django 3.0.6 on 2020-08-03 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0015_auto_20200803_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='likes',
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 16, 57, 37, 997070)),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 16, 57, 38, 12071)),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb1.Imagepost')),
            ],
        ),
    ]
