# Generated by Django 3.0.6 on 2020-08-03 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0016_auto_20200803_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 17, 46, 58, 386299)),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 17, 46, 58, 386299)),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
