# Generated by Django 3.0.6 on 2020-08-03 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0017_auto_20200803_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 8, 3, 18, 52, 52, 471826))),
            ],
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 18, 52, 52, 464826)),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 18, 52, 52, 468826)),
        ),
    ]
