# Generated by Django 3.0.6 on 2020-08-03 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0018_auto_20200803_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 20, 14, 42, 573233)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 20, 14, 42, 588833)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=222),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 20, 14, 42, 573233)),
        ),
    ]
