# Generated by Django 3.0.6 on 2020-08-03 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0020_auto_20200803_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 20, 38, 10, 541380)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 20, 38, 10, 546380)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='message',
            field=models.CharField(max_length=222),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 20, 38, 10, 544380)),
        ),
    ]
