# Generated by Django 3.0.6 on 2020-08-04 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0021_auto_20200803_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='message',
            new_name='message1',
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 6, 16, 30, 298387)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 6, 16, 30, 303387)),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 6, 16, 30, 301387)),
        ),
    ]
