# Generated by Django 3.0.6 on 2020-08-05 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0023_auto_20200805_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 12, 52, 29, 767736)),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='date',
            field=models.CharField(blank=True, max_length=422),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 12, 52, 29, 774737)),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 12, 52, 29, 772737)),
        ),
    ]
