# Generated by Django 3.0.6 on 2020-08-06 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb1', '0025_auto_20200805_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postcomment',
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 14, 44, 8, 929908)),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 14, 44, 8, 929908)),
        ),
    ]
