# Generated by Django 3.0.6 on 2020-08-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagelink', models.CharField(blank=True, max_length=422)),
                ('heading', models.CharField(blank=True, max_length=442)),
                ('body', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, max_length=422)),
            ],
        ),
    ]
